apiVersion: apps/v1
kind: Deployment
metadata:
   name: first-deployment
   labels:
      app: nginx
spec:
  replicas: 5
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 90%
      maxUnavailable: 25%
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.18
        imagePullPolicy: ifNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
